services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3010:4173"
    command: >
      sh -c "npm install --legacy-peer-deps && npm run build && npm run preview"

